project_name: bor

release:
  disable: false
  draft: false
  prerelease: auto

builds:
  - id: linux-amd64
    main: ./cmd/cli
    binary: bor
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    tags:
      - netgo
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container 
      -s -w -extldflags "-static"

nfpms:
  - vendor: 0xPolygon
    homepage: https://polygon.technology
    maintainer: Polygon Team <team@polygon.technology>
    description: Polygon Blockchain
    license: GPLv3 LGPLv3

    bindir: /usr/bin

    file_name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Arch }}"

    formats:
      - deb

# 禁用 tar.gz 归档文件
archives:
  - format: binary

# 禁用 checksums 文件
checksum:
  disable: true

snapshot:
  name_template: "{{ .Tag }}.next"

announce:
  slack:
    enabled: false

changelog:
  skip: true
